name: PowerItems
main: xyz.tangledwires.poweritems.PowerItems
version: 1.0.0
api-version: 1.20
author: YT_TangledWires
commands:
   testitem:
      description: Obtain the testing items
      usage: /testitem
      permission: poweritems.testitem
      permission-message: You don't have permission.
   createitem:
      description: Construct a new custom item
      usage: /createitem <internalName> <itemMaterial> <damageValue> <rarity> <itemName>
      permission: poweritems.createitem
      permission-message: You don't have permission.
   getitem:
      description: Get an item from the config file
      usage: /getitem <internalName>
      permission: poweritems.getitem
      permission-message: You don't have permission.