name: PowerItems
main: xyz.tangledwires.poweritems.PowerItems
version: 1.1.0
api-version: 1.20
author: YT_TangledWires
commands:
   testitem:
      description: Get the testing items
      usage: /testitem
      permission: poweritems.testitem
      permission-message: You don't have permission.
   createitem:
      description: Construct a new custom item
      usage: /createitem <itemID> <itemMaterial> <damage> <rarity> <itemName>
      permission: poweritems.createitem
      permission-message: You don't have permission.
   getitem:
      description: Get an item from the config file
      usage: /getitem <itemID>
      permission: poweritems.getitem
      permission-message: You don't have permission.
   commandtrigger:
      description: Manage command triggers on your held item
      usage: /commandtrigger <add|clear|list> <text>
      permission: poweritems.commandtrigger
      permission-message: You don't have permission.