name: PowerItems
main: xyz.tangledwires.poweritems.PowerItems
version: 0
api-version: 1.20
author: xWires
permissions:
   poweritems.usecommandtriggers:
      default: op
commands:
   testitem:
      description: Get the testing items
      usage: /testitem
      permission: poweritems.testitem
      permission-message: You don't have permission.
   createitem:
      description: Construct a new custom item
      usage: /createitem <itemID> <itemMaterial> <damage> <rarity> <itemName>
      permission: poweritems.createitem
      permission-message: You don't have permission.
   getitem:
      description: Get an item from the config file
      usage: /getitem <itemID>
      permission: poweritems.getitem
      permission-message: You don't have permission.
   commandtrigger:
      description: Manage command triggers on your held item
      usage: /commandtrigger <add|clear|list> <chat|command> <text>
      permission: poweritems.commandtrigger
      permission-message: You don't have permission.
   poweritems:
      description: Reload the PowerItems configuration file
      usage: /poweritems reload
      permission: poweritems.reload
      permission-message: You don't have permission.